version: '3.0'

services:
  nginx:
    image: nginx:latest
    ports:
     - "80:80"
    volumes:
     - ./www:/www
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./php
    volumes:
     - ./www:/www
    links:
     - db
  db:
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      MYSQL_DATABASE: 'magento'
      MYSQL_USER: 'magento'
      MYSQL_PASSWORD: 'magento'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db
volumes:
  db-data: